### ISSUE TITLE
Can I use the older version of puppeteer firefox when deploying to Heroku?

### ISSUE THREAD

**Issue by lehungson5011** [jontewks/heroku-buildpack-puppeteer-firefox#3]
Can I use the older version of puppeteer firefox (such as nightly firefox-96.0a1) when deploying to Heroku?
Please guide me the syntax code to do so. 
In package.json if I use this preinstall script: "PUPPETEER_PRODUCT=firefox npm install puppeteer", they will get the newest version and I do not want that
Thank you very much!

**Comment by jontewks** [comment]
Hey @lehungson5011 

From the puppeteer faq about installing firefox:
>Since Firefox support is experimental, Puppeteer downloads the latest [Firefox Nightly](https://wiki.mozilla.org/Nightly) when the PUPPETEER_PRODUCT environment variable is set to firefox. That's also why the value of firefox in [revisions.ts](https://github.com/puppeteer/puppeteer/blob/main/src/revisions.ts) is latest -- Puppeteer isn't tied to a particular Firefox version.

Looks like they install latest firefox. They point to their code where they set it to the latest version, perhaps you can edit the puppeteer code for that directly and then use your modified version instead of the npm installed one somehow.
