### ISSUE TITLE
could not find the executable_path

### ISSUE THREAD

**Issue by wanghaisheng** [jontewks/heroku-buildpack-puppeteer-firefox#4]
try:
            browser = playwright.firefox.launch(headless=headless)
            print('default is pass')
        except:
            executable_path=os.environ.get("firefox_executable_path")
            print('looking for env')
 
log keep to looking for env line

**Comment by MyJirapat** [comment]
: Starting process with command `node server.js`
2022-08-23T10:34:47.857252+00:00 app[web.1]: listen on port 44678...
2022-08-23T10:34:48.379291+00:00 heroku[web.1]: State changed from starting to up
2022-08-23T10:34:49.867176+00:00 app[web.1]: Error: Failed to launch the browser process! spawn C:/Program Files/Mozilla Firefox/firefox.exe ENOENT

**Comment by jontewks** [comment]
@wanghaisheng sorry just seeing this, didn't mean to ignore you for 5 months. 

I don't recognize that syntax, this buildpack is for getting puppeteer.js running using firefox. That doesn't look like Puppeteer code.

@MyJirapat Feel free to open a new issue rather than commenting on someone else's that doesn't seem to have to do with your issue. When you open a new issue please include your code as well as much as you can so I can reproduce your issue. 
Thanks!

**Comment by MyJirapat** [comment]
Thanks for your suggestion now I have opened an issue about a problem that
happened when deploying puppeteer-firefox on Heroku

ในวันที่ พฤ. 25 ส.ค. 2022 เวลา 02:28 Jon Tewksbury ***@***.***>
เขียนว่า:
